// Generated types (would be auto-generated by typeshare in production)

export interface BookSummary {
  id: string;
  title: string;
  authors: string[];
  language: string;
}

export interface BookResponse {
  id: string;
  title: string;
  authors: string[];
  description?: string;
  language: string;
  chapters: ChapterSummary[];
}

export interface ChapterSummary {
  title: string;
  index: number;
}

export interface ListBooksResponse {
  books: BookSummary[];
  total: number;
  page: number;
  per_page: number;
}

export interface UploadResponse {
  id: string;
  title: string;
  message: string;
}

// Block types for rendering
export type Block =
  | { type: 'header'; level: number; content: Inline[]; anchor?: string }
  | { type: 'paragraph'; content: Inline[] }
  | { type: 'list'; items: Block[][]; ordered: boolean }
  | { type: 'image'; resource_key: string; caption?: string; alt: string }
  | { type: 'code_block'; lang?: string; code: string }
  | { type: 'blockquote'; content: Block[] }
  | { type: 'thematic_break' }
  | { type: 'table'; data: TableData }
  | { type: 'footnote'; id: string; content: Block[] };

export type Inline =
  | { type: 'text'; content: string }
  | { type: 'bold'; children: Inline[] }
  | { type: 'italic'; children: Inline[] }
  | { type: 'code'; content: string }
  | { type: 'link'; children: Inline[]; url: string }
  | { type: 'superscript'; children: Inline[] }
  | { type: 'subscript'; children: Inline[] }
  | { type: 'strikethrough'; children: Inline[] }
  | { type: 'footnote_ref'; id: string }
  | { type: 'ruby'; base: string; annotation: string }
  | { type: 'break' };

export interface TableData {
  headers: TableCell[];
  rows: TableCell[][];
}

export interface TableCell {
  content: Inline[];
  colspan: number;
  rowspan: number;
}
